{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-latex2exp
  version: {{ version|replace("-", "_") }}

source:
  fn: latex2exp_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/latex2exp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/latex2exp/latex2exp_{{ version }}.tar.gz
  sha256: 6f3b3e6c543aaee5617a8890c272c1f3e08a88754892e4f3d27f71fe0fbf7662

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-magrittr
    - r-stringr
  run:
    - r-base
    - r-magrittr
    - r-stringr

test:
  commands:
    - $R -e "library('latex2exp')"           # [not win]
    - "\"%R%\" -e \"library('latex2exp')\""  # [win]

about:
  home: http://github.com/stefano-meschiari/latex2exp
  license: MIT
  summary: Parses and converts LaTeX math formulas to R's plotmath expressions, used to enter mathematical formulas and symbols to be rendered as text, axis labels, etc. throughout R's plotting system.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - apcamargo
