# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "yjtVDsQouFYAsReu591qmDPoU9kaxqLqg1ZFuTX84F+4LpVvSO2rXjkk6GDYmlYFKfEgkYvE2aXAL2oA8BJtblxUF2TOPe6RL/lJcKpCNmNEWiOk8BiG1Anp2eVNTXsZ3HGQ3W5M+gx8JRxuq5e26cWEyhH8/cBOvV3EHjDxXtKfo7/gUsQGlMISjfVXvLGX+VheWuHuN46gChAqJL7RHdUXJbXN2Y+4ur6BrUU5BLzu8IiRF7G/inNA6xIpczcvvLoDIJwZl1sRsO85bWbJny76MO/EVv1gP5i18zPr80mhUZZtcuk+3pSsL6JE57GIhLBfa9T6N5z5wyLE/nuzULIF1iRYNksNuBtuhMMjS1SAcZsn+Sta8Y5iFLdA8vz1A+NmvmKHwV+bJGVWyUWmPeyiDPPfiUeaOEzD1FK6M8J7BSrlGWEalENrAsm+F1uODqffvfNevYlRaIjMvad85MH7t+GWaktzrVphTSNm5khyqtOetezACrJ01FN+HTqSqrI2MjrXSO0zB9929UgOkU5GYmaNLLycwV7mW2yTgaAg1HojlXClqZXEyfDnZc9H3Y50WDBVBo36cJuWkTXg1xXFxCuXxhLysnY5i/l8QGI/vm6mg9wEEm9MEMeLFXkOJShSZ9vrn9PkOz6wTsTKK09d5f5E6wy11DTuuOKUH+Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
