appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: yjtVDsQouFYAsReu591qmDPoU9kaxqLqg1ZFuTX84F+4LpVvSO2rXjkk6GDYmlYFKfEgkYvE2aXAL2oA8BJtblxUF2TOPe6RL/lJcKpCNmNEWiOk8BiG1Anp2eVNTXsZ3HGQ3W5M+gx8JRxuq5e26cWEyhH8/cBOvV3EHjDxXtKfo7/gUsQGlMISjfVXvLGX+VheWuHuN46gChAqJL7RHdUXJbXN2Y+4ur6BrUU5BLzu8IiRF7G/inNA6xIpczcvvLoDIJwZl1sRsO85bWbJny76MO/EVv1gP5i18zPr80mhUZZtcuk+3pSsL6JE57GIhLBfa9T6N5z5wyLE/nuzULIF1iRYNksNuBtuhMMjS1SAcZsn+Sta8Y5iFLdA8vz1A+NmvmKHwV+bJGVWyUWmPeyiDPPfiUeaOEzD1FK6M8J7BSrlGWEalENrAsm+F1uODqffvfNevYlRaIjMvad85MH7t+GWaktzrVphTSNm5khyqtOetezACrJ01FN+HTqSqrI2MjrXSO0zB9929UgOkU5GYmaNLLycwV7mW2yTgaAg1HojlXClqZXEyfDnZc9H3Y50WDBVBo36cJuWkTXg1xXFxCuXxhLysnY5i/l8QGI/vm6mg9wEEm9MEMeLFXkOJShSZ9vrn9PkOz6wTsTKK09d5f5E6wy11DTuuOKUH+Y=
conda_forge_output_validation: true
